In [3]:
import numpy as np

In [3]:
mylist = [1,2,3]

In [4]:
x = np.array(mylist)

In [6]:
type(x)

numpy.ndarray

In [7]:
my_matrix = [[1,2,3],[0,9,1],[-2,5,7]]

In [11]:
m = np.array(my_matrix)

In [12]:
type(m)

numpy.ndarray

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.linspace(0,100,51)

array([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,
        22.,  24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,
        44.,  46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,
        66.,  68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,
        88.,  90.,  92.,  94.,  96.,  98., 100.])

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
np.random.rand(5,5)

array([[0.98134793, 0.77154742, 0.80974705, 0.17147882, 0.77086487],
       [0.41116573, 0.59278238, 0.41606272, 0.20572257, 0.5853976 ],
       [0.21708915, 0.11317623, 0.37910737, 0.49854   , 0.93846804],
       [0.57352061, 0.99826941, 0.47757823, 0.65288109, 0.08770835],
       [0.69046562, 0.04049175, 0.32060991, 0.48993252, 0.30965873]])

In [49]:
np.random.randn(5,5)

array([[-0.49276777, -0.0439504 ,  1.15762064, -0.5789026 ,  0.14535974],
       [ 0.14256144, -0.22263846, -0.32424205,  0.31932887, -0.38774781],
       [ 1.25221964, -0.18124344,  0.47116708, -0.4122981 , -0.77373534],
       [ 1.8224079 ,  0.50166177,  0.47993247, -2.08088405, -2.39019836],
       [ 0.08882933,  1.93510455, -1.11161116,  0.66294314,  1.79866645]])

In [82]:
np.random.randint(1,1000,5)

array([ 82, 497, 947,  36,   4])

In [83]:
arr = np.arange(25)

In [86]:
ranarr = np.random.randint(0,50,10)

In [92]:
ranarr.reshape(1,10)

array([[30, 32, 32, 12,  2, 23,  4, 31, 43,  4]])

In [95]:
ranarr.dtype

dtype('int32')

In [108]:
ranarr.argmax()

8

In [114]:
arr = np.arange(0,11)

In [110]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
arr[8]

8

In [112]:
arr[:5] = 10

In [113]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9, 10])

In [115]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [116]:
slicearr = arr[:3]

In [117]:
slicearr

array([0, 1, 2])

In [118]:
slicearr[:] = 55

In [119]:
slicearr

array([55, 55, 55])

In [120]:
arr

array([55, 55, 55,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
mat = np.array([[1,5,8],[7,3,0],[9,11,4]])

In [5]:
mat

array([[ 1,  5,  8],
       [ 7,  3,  0],
       [ 9, 11,  4]])

In [125]:
mat[0,1]

5

In [126]:
mat[0][1]

5

In [6]:
mat[0]

array([1, 5, 8])

In [20]:
mat[1:,1:]

array([[ 3,  0],
       [11,  4]])

In [21]:
arr = np.arange(1,11)

In [27]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
bool_array = arr>3

In [26]:
arr[bool_array]

array([ 4,  5,  6,  7,  8,  9, 10])

In [33]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [42]:
np.setdiff1d(np.arange(12,26),np.array([16,21])).reshape(3,4)

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [43]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [47]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])